-- Revoked Tokens table (H2)
create table if not exists revoked_tokens (
    id bigint generated by default as identity primary key,
    token varchar(500) not null unique,
    expires_at timestamp not null
);

create index if not exists idx_revoked_tokens_expires_at on revoked_tokens(expires_at);
