name: Checkstyle

on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master, main ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      # Run BOTH main and test checks (or just `./gradlew check`)
      - name: Run Checkstyle
        run: ./gradlew --no-daemon clean checkstyleMain checkstyleTest

      # Upload reports so authors can open them from the PR
      - name: Upload Checkstyle reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-reports
          path: build/reports/checkstyle/
